services:
  web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./web/:/app
      - node_modules:/app/node_modules:rw
  auth:
    build:
      context: ./
      dockerfile: ./auth/Dockerfile
    tty: true
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      ENV: local
    secrets:
      - auth_privatekey
      - auth_publickey
  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    tty: true
    ports:
      - 8081:8081
    environment:
      ENV: local
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "9000:8080"
    volumes:
      - ./app/doc/api/task-api.yaml:/usr/share/nginx/html/task-api.yaml
      - ./auth/doc/api/auth-api.yaml:/usr/share/nginx/html/auth-api.yaml
    environment:
      API_URL: /task-api.yaml
secrets:
  auth_privatekey:
    file: auth/crt/privatekey.pem
  auth_publickey:
    file: auth/crt/pubkey.pem
volumes:
  node_modules:
