services:
  web:
    build:
      dockerfile: ./web/Dockerfile.local
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - ./web/:/app
      - node_modules:/app/node_modules:rw
volumes:
  node_modules:
