spring:
  application:
    name: app
logging:
  level:
    root: INFO
server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
  tomcat:
    accept-count: 500
    max-connections: 10000
    threads:
      max: 500
      min-spare: 500
grpc:
  client:
    verify:
      address: 'static://task-manage-auth-1:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext