openapi: "3.0.2"
info:
  title: タスク管理API
  version: "1.0"
servers:
  - url: http://localhost:9000/
# TODO　レスポンスコード200以外のレスポンスを追加する
paths:
  /board:
    post:
      summary: "ボード作成"
      parameters:
        - $ref: '#/components/parameters/Token'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Board'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Board'
  /boards:
    get:
      summary: "ボード一覧取得"
      parameters:
        - $ref: '#/components/parameters/Token'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Board'
  /board/{boardId}:
    get:
      summary: "ボード取得"
      parameters:
        - $ref: '#/components/parameters/Token'
        - in: path
          name: boardId
          required: true
          description: ボードID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoardWithTaskMember'
    post:
      summary: "ボード更新"
      parameters:
        - $ref: '#/components/parameters/Token'
        - in: path
          name: boardId
          required: true
          description: ボードID
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoardWithTaskMember'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BoardWithTaskMember'
    delete:
      parameters:
        - $ref: '#/components/parameters/Token'
        - in: path
          name: boardId
          required: true
          description: ボードID
          schema:
            type: string
      response:
        '200':
          description: OK
  /task:
    post:
      summary: "タスク追加"
      parameters:
        - $ref: '#/components/parameters/Token'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCard'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskCard'
  /tasks:
    get:
      summary: "タスク一覧取得"
      parameters:
        - $ref: '#/components/parameters/Token'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListParam'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
  /task/{taskId}:
    get:
      summary: "タスク取得"
      parameters:
        - $ref: '#/components/parameters/Token'
        - in: path
          name: taskId
          required: true
          description: タスクID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: "タスク更新"
      parameters:
        - $ref: '#/components/parameters/Token'
        - in: path
          name: taskId
          required: true
          description: タスクID
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Task'
    delete:
      summary: "タスク削除"
      parameters:
        - $ref: '#/components/parameters/Token'
        - in: path
          name: taskId
          required: true
          description: タスクID
          schema:
            type: string
      responses:
        '200':
          description: OK

components:
  parameters:
    Token:
      in: header
      name: Authorization
      schema:
        type: string
        default: Bearer <token>
      required: true
      description: 認証トークン
  schemas:
    Board:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: ボードID(ULID)
        name:
          type: string
          description: ボード名
    BoardWithTaskMember:
      type: object
      required:
        - id
        - name
        - members
      properties:
        id:
          type: string
          description: ボードID(ULID)
        name:
          type: string
          description: ボード名
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
        memberIds:
          type: array
          description: メンバーID(ULID)の配列
          items:
            type: string
    TaskCard:
      type: object
      required:
        - boardId
        - name
      properties:
        boardId:
          type: string
          description: ボードID
        taskId:
          type: string
          description: タスクID
        name:
          type: string
          description: タスク名
    Task:
      type: object
      required:
        - boardId 
        - name
      properties:
        boardId:
          type: string
          description: ボードID
        taskId:
          type: string
          description: タスクID(ULID)
        name:
          type: string
          description: タスク名
        task_description:
          type: string
          description: タスク説明
        deadline_date:
          type: string
          format: date
          description: 期限
        is_completed:
          type: boolean
          default: false
          description: 完了フラグ
    ListParam:
      properties:
        offset:
          required: true
          type: integer
          description: オフセット
        limit:
          type: integer
          default: 20
          description: 最大取得件数