openapi: "3.0.2"
info:
  title: タスク管理API
  version: "1.0"
servers:
  - url: http://localhost:9000/
# TODO　レスポンスコード200以外のレスポンスを追加する
paths:
  /login:
    post:
      summary: ログイン
      requestBody:
        content:
          application/json:
            schema:
              properties:
                id:
                  type: string
                  description: ログインID
                password:
                  type: string
                  description: パスワード
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  token:
                    type: string
                    description: 認証トークン
