FROM node:22.6.0-bullseye-slim

ENV APP /app

USER 1000:1000
WORKDIR $APP
COPY --chown=1000:1000 ["./web/package.json", "./web/package-lock.json", "${APP}"]
RUN npm update && \
  npm install

COPY ./web $APP
EXPOSE 5173